-- Auto-generated by scripts/check_migrations.py — do not edit by hand.
-- Run this in the Supabase SQL Editor to see which migrations are pending.

WITH local_migrations(version, filename) AS (
  VALUES
    ('00002', '00002_words_select_policy.sql'),
    ('20260226120000', '20260226120000_srs.sql'),
    ('20260226140000', '20260226140000_srs_cloze_api.sql'),
    ('20260316141903', '20260316141903_user_settings.sql'),
    ('20260325120000', '20260325120000_align_database_context.sql'),
    ('20260326090000', '20260326090000_record_review_card_type.sql'),
    ('20260326133000', '20260326133000_add_cloze_and_normal_direction_settings.sql'),
    ('20260401110000', '20260401110000_add_auto_advance_correct_setting.sql'),
    ('20260401123000', '20260401123000_reader_manual_saved_decks.sql'),
    ('20260404185512', '20260404185512_replace_word_data_layer_with_canonical_words.sql'),
    ('20260407124616', '20260407124616_support_new_spa_seed_headers.sql'),
    ('20260407125544', '20260407125544_split_definitions_from_words_and_persist_tags.sql'),
    ('20260409182000', '20260409182000_add_sentence_translation_visibility_setting.sql'),
    ('20260409201500', '20260409201500_add_text_collections_and_reader_chunk_metadata.sql'),
    ('20260409213000', '20260409213000_seed_reader_demo_content.sql'),
    ('20260410103000', '20260410103000_add_daily_session_reading_and_listening_progress.sql'),
    ('20260410140000', '20260410140000_add_dissertation_metrics_instrumentation.sql'),
    ('20260410160000', '20260410160000_add_study_enrollments.sql'),
    ('20260410160001', '20260410160001_srs_v2_scheduler.sql')
)
SELECT
  lm.version,
  lm.filename,
  CASE
    WHEN sm.version IS NOT NULL THEN 'applied'
    ELSE 'PENDING - needs to be run manually'
  END AS status
FROM local_migrations lm
LEFT JOIN supabase_migrations.schema_migrations sm
  ON sm.version = lm.version
ORDER BY lm.version;
