import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Extract the human title from a listening passage .txt file.
 *
 * The title is on the first line, wrapped in triple dashes:
 *   ---Hoy es mi primer día en una clase de español---
 *
 * Returns null if the title cannot be parsed.
 */
export function extractTitleFromPassageFile(filePath: string): string | null {
  if (!fs.existsSync(filePath)) return null;

  const firstLine = fs.readFileSync(filePath, "utf-8").split("\n")[0]?.trim();
  if (!firstLine) return null;

  const match = firstLine.match(/^---(.+)---$/);
  if (!match || !match[1]?.trim()) return null;

  return match[1].trim();
}

/**
 * Extract title and topic from the paired JSON metadata file.
 *
 * JSON files live in all_passages_renamed/ with the naming convention:
 *   {cefr}_{mode}_stage{N}_{passageNum}.json
 *
 * e.g. a1_short_stage1_3.json
 */
export function extractMetaFromJson(jsonPath: string): { title: string | null; topic: string | null } {
  if (!fs.existsSync(jsonPath)) return { title: null, topic: null };

  try {
    const data = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
    return {
      title: typeof data.title === "string" && data.title.trim() ? data.title.trim() : null,
      topic: typeof data.topic === "string" && data.topic.trim() ? data.topic.trim() : null,
    };
  } catch {
    return { title: null, topic: null };
  }
}

/**
 * Convert a listening passage .txt filename to the corresponding JSON metadata path.
 *
 * .txt: a1_short_stage1_passage3.txt
 * .json: a1_short_stage1_3.json
 */
export function txtFilenameToJsonFilename(txtFilename: string): string | null {
  const match = txtFilename.match(
    /^([a-c][12])_(short|medium|long|very_long)_stage(\d+)_passage(\d+)\.txt$/,
  );
  if (!match) return null;
  const [, cefr, mode, stageNum, passageNum] = match;
  return `${cefr}_${mode}_stage${stageNum}_${passageNum}.json`;
}

/**
 * Detect if a title is a generic placeholder generated by the pipeline.
 *
 * Patterns like:
 *   "A1 Short – Stage 1 Passage 1"
 *   "Listening: A1 Short – Stage 1 Passage 1"
 *   "a1 short stage 1 passage 1"
 */
export function isGenericTitle(title: string): boolean {
  const normalized = title
    .replace(/^listening:\s*/i, "")
    .replace(/[–—-]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();

  // Pattern: {cefr} {mode} stage {N} passage {N}
  return /^[a-c][12]\+?\+?\s+(short|medium|long|very long)\s+stage\s+\d+\s+passage\s+\d+$/i.test(normalized);
}

/**
 * Resolve the listening passage .txt filename from DB text metadata.
 *
 * DB stores: stage="listening_stage_3", passage_mode="short", passage_number=1, difficulty_cefr="A1"
 * Returns: "a1_short_stage3_passage1.txt"
 */
export function resolvePassageFilename(
  difficultyCefr: string,
  passageMode: string,
  stageNum: number,
  passageNumber: number,
): string {
  const cefr = difficultyCefr.toLowerCase();
  return `${cefr}_${passageMode}_stage${stageNum}_passage${passageNumber}.txt`;
}

/**
 * Get all metadata for a listening passage given its DB row fields.
 * Looks up the .txt file for the real title and the .json file for topic.
 */
export function getPassageMetadata(
  listeningPassagesDir: string,
  jsonMetadataDir: string,
  difficultyCefr: string,
  passageMode: string,
  stageNum: number,
  passageNumber: number,
): { humanTitle: string | null; topic: string | null; txtFile: string; jsonFile: string | null } {
  const txtFile = resolvePassageFilename(difficultyCefr, passageMode, stageNum, passageNumber);
  const txtPath = path.join(listeningPassagesDir, txtFile);
  const humanTitle = extractTitleFromPassageFile(txtPath);

  const jsonFile = txtFilenameToJsonFilename(txtFile);
  const jsonPath = jsonFile ? path.join(jsonMetadataDir, jsonFile) : null;
  const jsonMeta = jsonPath ? extractMetaFromJson(jsonPath) : { title: null, topic: null };

  return {
    humanTitle,
    topic: jsonMeta.topic,
    txtFile,
    jsonFile,
  };
}
