/**
 * AUTOGENERATED by scripts/compute_onboarding_coverage.ts — do not edit by hand.
 *
 * Estimated vocabulary coverage derived from tokenising the static
 * reading_passages/ corpus. For each bucket N, the coverage value is the
 * fraction of running tokens in the corpus whose within-corpus frequency
 * rank is <= N. The curve is sampled on a log-scaled rank axis so the
 * high-payoff early region is visible.
 *
 * Source stats at generation time:
 *   passages:        385
 *   total tokens:    47305
 *   unique types:    6575
 */

export type CoverageRankPoint = {
  readonly rank: number;
  readonly coverage: number;
};

export type CoverageBucket = {
  readonly bucket: number;
  readonly coverage: number;
};

export const COVERAGE_CORPUS_STATS = {
  passages: 385,
  totalTokens: 47305,
  uniqueTypes: 6575,
} as const;

export const COVERAGE_BUCKETS: readonly CoverageBucket[] = [
  {
    "bucket": 100,
    "coverage": 0.534552
  },
  {
    "bucket": 500,
    "coverage": 0.713878
  },
  {
    "bucket": 1000,
    "coverage": 0.791291
  },
  {
    "bucket": 2000,
    "coverage": 0.873671
  },
  {
    "bucket": 5000,
    "coverage": 0.966705
  }
] as const;

/**
 * Monotone-increasing (rank, coverage) samples from the app's reading
 * corpus. The runtime helper computes the on-screen x position from rank
 * so the curve and the marker share a single x mapping.
 */
export const COVERAGE_CURVE: readonly CoverageRankPoint[] = [
  {
    "rank": 1,
    "coverage": 0.043949
  },
  {
    "rank": 2,
    "coverage": 0.086101
  },
  {
    "rank": 3,
    "coverage": 0.117366
  },
  {
    "rank": 4,
    "coverage": 0.146137
  },
  {
    "rank": 5,
    "coverage": 0.168354
  },
  {
    "rank": 6,
    "coverage": 0.184568
  },
  {
    "rank": 7,
    "coverage": 0.199387
  },
  {
    "rank": 8,
    "coverage": 0.213825
  },
  {
    "rank": 9,
    "coverage": 0.2282
  },
  {
    "rank": 10,
    "coverage": 0.241856
  },
  {
    "rank": 11,
    "coverage": 0.255089
  },
  {
    "rank": 12,
    "coverage": 0.268238
  },
  {
    "rank": 13,
    "coverage": 0.28014
  },
  {
    "rank": 14,
    "coverage": 0.291069
  },
  {
    "rank": 15,
    "coverage": 0.300772
  },
  {
    "rank": 16,
    "coverage": 0.310115
  },
  {
    "rank": 18,
    "coverage": 0.325653
  },
  {
    "rank": 19,
    "coverage": 0.33246
  },
  {
    "rank": 20,
    "coverage": 0.338949
  },
  {
    "rank": 22,
    "coverage": 0.351633
  },
  {
    "rank": 23,
    "coverage": 0.357658
  },
  {
    "rank": 25,
    "coverage": 0.368735
  },
  {
    "rank": 27,
    "coverage": 0.378057
  },
  {
    "rank": 29,
    "coverage": 0.387063
  },
  {
    "rank": 31,
    "coverage": 0.395096
  },
  {
    "rank": 33,
    "coverage": 0.402494
  },
  {
    "rank": 36,
    "coverage": 0.412451
  },
  {
    "rank": 38,
    "coverage": 0.418412
  },
  {
    "rank": 41,
    "coverage": 0.426361
  },
  {
    "rank": 44,
    "coverage": 0.433929
  },
  {
    "rank": 48,
    "coverage": 0.443695
  },
  {
    "rank": 51,
    "coverage": 0.450756
  },
  {
    "rank": 55,
    "coverage": 0.459761
  },
  {
    "rank": 59,
    "coverage": 0.468386
  },
  {
    "rank": 64,
    "coverage": 0.478427
  },
  {
    "rank": 68,
    "coverage": 0.486101
  },
  {
    "rank": 73,
    "coverage": 0.495212
  },
  {
    "rank": 79,
    "coverage": 0.505274
  },
  {
    "rank": 85,
    "coverage": 0.514237
  },
  {
    "rank": 91,
    "coverage": 0.522735
  },
  {
    "rank": 98,
    "coverage": 0.532037
  },
  {
    "rank": 105,
    "coverage": 0.540725
  },
  {
    "rank": 113,
    "coverage": 0.549477
  },
  {
    "rank": 121,
    "coverage": 0.55732
  },
  {
    "rank": 130,
    "coverage": 0.565522
  },
  {
    "rank": 140,
    "coverage": 0.573745
  },
  {
    "rank": 150,
    "coverage": 0.581059
  },
  {
    "rank": 161,
    "coverage": 0.588796
  },
  {
    "rank": 173,
    "coverage": 0.596681
  },
  {
    "rank": 186,
    "coverage": 0.604672
  },
  {
    "rank": 200,
    "coverage": 0.612705
  },
  {
    "rank": 214,
    "coverage": 0.620252
  },
  {
    "rank": 230,
    "coverage": 0.628433
  },
  {
    "rank": 247,
    "coverage": 0.636423
  },
  {
    "rank": 266,
    "coverage": 0.644668
  },
  {
    "rank": 286,
    "coverage": 0.652531
  },
  {
    "rank": 307,
    "coverage": 0.660205
  },
  {
    "rank": 329,
    "coverage": 0.667752
  },
  {
    "rank": 354,
    "coverage": 0.675764
  },
  {
    "rank": 380,
    "coverage": 0.683458
  },
  {
    "rank": 408,
    "coverage": 0.69128
  },
  {
    "rank": 439,
    "coverage": 0.699482
  },
  {
    "rank": 471,
    "coverage": 0.707219
  },
  {
    "rank": 506,
    "coverage": 0.715146
  },
  {
    "rank": 544,
    "coverage": 0.723179
  },
  {
    "rank": 584,
    "coverage": 0.730916
  },
  {
    "rank": 627,
    "coverage": 0.738823
  },
  {
    "rank": 674,
    "coverage": 0.746771
  },
  {
    "rank": 724,
    "coverage": 0.754804
  },
  {
    "rank": 778,
    "coverage": 0.762795
  },
  {
    "rank": 835,
    "coverage": 0.770828
  },
  {
    "rank": 897,
    "coverage": 0.778691
  },
  {
    "rank": 964,
    "coverage": 0.78719
  },
  {
    "rank": 1035,
    "coverage": 0.79499
  },
  {
    "rank": 1112,
    "coverage": 0.803129
  },
  {
    "rank": 1195,
    "coverage": 0.811901
  },
  {
    "rank": 1283,
    "coverage": 0.821203
  },
  {
    "rank": 1379,
    "coverage": 0.829553
  },
  {
    "rank": 1481,
    "coverage": 0.838178
  },
  {
    "rank": 1591,
    "coverage": 0.847479
  },
  {
    "rank": 1709,
    "coverage": 0.855216
  },
  {
    "rank": 1836,
    "coverage": 0.86327
  },
  {
    "rank": 1972,
    "coverage": 0.871895
  },
  {
    "rank": 2118,
    "coverage": 0.881154
  },
  {
    "rank": 2275,
    "coverage": 0.888363
  },
  {
    "rank": 2444,
    "coverage": 0.895508
  },
  {
    "rank": 2626,
    "coverage": 0.903203
  },
  {
    "rank": 2820,
    "coverage": 0.911405
  },
  {
    "rank": 3030,
    "coverage": 0.920283
  },
  {
    "rank": 3254,
    "coverage": 0.929754
  },
  {
    "rank": 3496,
    "coverage": 0.934912
  },
  {
    "rank": 3755,
    "coverage": 0.940387
  },
  {
    "rank": 4034,
    "coverage": 0.946285
  },
  {
    "rank": 4333,
    "coverage": 0.952605
  },
  {
    "rank": 4655,
    "coverage": 0.959412
  },
  {
    "rank": 5000,
    "coverage": 0.966705
  }
] as const;
