/**
 * Build-time helper: walks the static reading_passages/ corpus, tokenises all
 * passage_text, derives within-corpus word frequency ranks, and computes
 * estimated text coverage for each onboarding bucket (top-N most frequent
 * words). Writes the result as a committed JSON constant the onboarding
 * graph reads at runtime.
 *
 * Run: `npx tsx scripts/compute_onboarding_coverage.ts`
 *
 * This runs offline and depends on nothing other than the checked-in
 * passages, so the output is deterministic and reproducible.
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(__dirname, "..");
const PASSAGES_DIR = join(ROOT, "reading_passages");
const OUT = join(ROOT, "lib/onboarding/coverageData.ts");

const BUCKETS = [100, 500, 1000, 2000, 5000] as const;

// Mirrors lib/reader/tokenize.ts (inlined so this script has no deps).
const TOKEN_RE =
  /(\p{L}[\p{L}\p{M}]*(?:['’-]\p{L}[\p{L}\p{M}]*)*|\s+|[^\s\p{L}\p{M}]+)/gu;
const WORD_RE = /^\p{L}[\p{L}\p{M}]*(?:['’-]\p{L}[\p{L}\p{M}]*)*$/u;

function normalize(s: string): string {
  return s.trim().toLocaleLowerCase("es");
}

function tokenizeWords(text: string): string[] {
  const out: string[] = [];
  for (const m of text.matchAll(TOKEN_RE)) {
    const surface = m[0];
    if (WORD_RE.test(surface)) out.push(normalize(surface));
  }
  return out;
}

function* walkJson(dir: string): Generator<string> {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) yield* walkJson(p);
    else if (st.isFile() && name.endsWith(".json")) yield p;
  }
}

const freq = new Map<string, number>();
let totalTokens = 0;
let passagesUsed = 0;

for (const file of walkJson(PASSAGES_DIR)) {
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(file, "utf8"));
  } catch {
    continue;
  }
  if (!raw || typeof raw !== "object") continue;
  const text = (raw as { passage_text?: unknown }).passage_text;
  if (typeof text !== "string" || text.length === 0) continue;
  passagesUsed += 1;
  for (const tok of tokenizeWords(text)) {
    freq.set(tok, (freq.get(tok) ?? 0) + 1);
    totalTokens += 1;
  }
}

// Rank words by descending frequency. Deterministic tiebreaker on the word
// itself so re-runs produce byte-identical output.
const ranked = [...freq.entries()].sort((a, b) => {
  if (b[1] !== a[1]) return b[1] - a[1];
  return a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0;
});

// Cumulative token count covered by the top-k words.
const cumulativeByRank: number[] = new Array(ranked.length + 1).fill(0);
for (let i = 0; i < ranked.length; i++) {
  cumulativeByRank[i + 1] = cumulativeByRank[i] + ranked[i][1];
}

function coverageAt(topN: number): number {
  const k = Math.min(topN, ranked.length);
  return cumulativeByRank[k] / totalTokens;
}

const bucketCoverage = BUCKETS.map((b) => ({
  bucket: b,
  coverage: coverageAt(b),
}));

// Dense rank-anchored curve clamped to MAX_RANK. We store (rank, coverage)
// only — the runtime helper derives the on-screen x position from rank via
// topNXPosition, so the curve and the marker always share a single source of
// truth for the x mapping.
const MAX_RANK = BUCKETS[BUCKETS.length - 1];
const SAMPLE_COUNT = 120;
const logMax = Math.log(MAX_RANK);
const curve: Array<{ rank: number; coverage: number }> = [];
const seenRanks = new Set<number>();
for (let i = 0; i < SAMPLE_COUNT; i++) {
  const t = i / (SAMPLE_COUNT - 1);
  const rank = Math.max(1, Math.round(Math.exp(t * logMax)));
  if (seenRanks.has(rank)) continue;
  seenRanks.add(rank);
  curve.push({ rank, coverage: coverageAt(rank) });
}

const fileHeader = `/**
 * AUTOGENERATED by scripts/compute_onboarding_coverage.ts — do not edit by hand.
 *
 * Estimated vocabulary coverage derived from tokenising the static
 * reading_passages/ corpus. For each bucket N, the coverage value is the
 * fraction of running tokens in the corpus whose within-corpus frequency
 * rank is <= N. The curve is sampled on a log-scaled rank axis so the
 * high-payoff early region is visible.
 *
 * Source stats at generation time:
 *   passages:        ${passagesUsed}
 *   total tokens:    ${totalTokens}
 *   unique types:    ${ranked.length}
 */

export type CoverageRankPoint = {
  readonly rank: number;
  readonly coverage: number;
};

export type CoverageBucket = {
  readonly bucket: number;
  readonly coverage: number;
};

export const COVERAGE_CORPUS_STATS = {
  passages: ${passagesUsed},
  totalTokens: ${totalTokens},
  uniqueTypes: ${ranked.length},
} as const;

export const COVERAGE_BUCKETS: readonly CoverageBucket[] = ${JSON.stringify(
  bucketCoverage.map((b) => ({
    bucket: b.bucket,
    coverage: Number(b.coverage.toFixed(6)),
  })),
  null,
  2,
)} as const;

/**
 * Monotone-increasing (rank, coverage) samples from the app's reading
 * corpus. The runtime helper computes the on-screen x position from rank
 * so the curve and the marker share a single x mapping.
 */
export const COVERAGE_CURVE: readonly CoverageRankPoint[] = ${JSON.stringify(
  curve.map((p) => ({
    rank: p.rank,
    coverage: Number(p.coverage.toFixed(6)),
  })),
  null,
  2,
)} as const;
`;

writeFileSync(OUT, fileHeader);
console.log(
  `wrote ${relative(ROOT, OUT)}  (passages=${passagesUsed}, tokens=${totalTokens}, types=${ranked.length})`,
);
for (const b of bucketCoverage) {
  console.log(`  top-${b.bucket}: ${(b.coverage * 100).toFixed(1)}% coverage`);
}
