#!/usr/bin/env python3

from __future__ import annotations

import csv
import sys
from pathlib import Path

BATCH_SIZE = 500
EXPECTED_HEADERS = [
    "rank",
    "lemma",
    "original_lemma",
    "translation",
    "definitions",
    "english_definition",
    "pos",
    "sentence",
    "english_sentence",
]


def sql_string(value: str | None) -> str:
    if value is None:
        return "NULL"
    normalized = value.replace("\r\n", "\n").replace("\r", "\n")
    return "'" + normalized.replace("'", "''") + "'"


def sql_integer(value: str | None) -> str:
    if value is None:
        return "NULL"
    stripped = value.strip()
    if not stripped:
        return "NULL"
    return str(int(stripped))


def row_to_sql_values(row: dict[str, str]) -> str:
    return "(" + ", ".join(
        [
            sql_integer(row.get("rank")),
            sql_string(row.get("lemma")),
            sql_string(row.get("original_lemma")),
            sql_string(row.get("translation")),
            sql_string(row.get("definitions")),
            sql_string(row.get("english_definition")),
            sql_string(row.get("pos")),
            sql_string(row.get("sentence")),
            sql_string(row.get("english_sentence")),
        ]
    ) + ")"


def main() -> int:
    if len(sys.argv) != 3:
        print(
            "Usage: generate_words_import_sql.py <input_csv> <output_sql>",
            file=sys.stderr,
        )
        return 1

    input_csv = Path(sys.argv[1])
    output_sql = Path(sys.argv[2])

    if not input_csv.exists():
        print(f"Input CSV not found: {input_csv}", file=sys.stderr)
        return 1

    output_sql.parent.mkdir(parents=True, exist_ok=True)

    with input_csv.open(newline="", encoding="utf-8") as csv_file:
        reader = csv.DictReader(csv_file)
        if reader.fieldnames != EXPECTED_HEADERS:
            print(
                f"Unexpected CSV headers: {reader.fieldnames!r}",
                file=sys.stderr,
            )
            return 1

        rows = list(reader)

    with output_sql.open("w", encoding="utf-8") as sql_file:
        sql_file.write("-- Generated by scripts/generate_words_import_sql.py\n")
        sql_file.write("BEGIN;\n\n")
        sql_file.write("TRUNCATE TABLE public.words_import_raw;\n\n")

        for start in range(0, len(rows), BATCH_SIZE):
            batch = rows[start : start + BATCH_SIZE]
            sql_file.write(
                "INSERT INTO public.words_import_raw (rank, lemma, original_lemma, translation, definitions, english_definition, pos, sentence, english_sentence)\nVALUES\n"
            )
            sql_file.write(",\n".join(row_to_sql_values(row) for row in batch))
            sql_file.write(";\n\n")

        sql_file.write(
            """WITH normalized AS (
  SELECT
    rank,
    btrim(lemma) AS lemma,
    COALESCE(NULLIF(btrim(original_lemma), ''), btrim(lemma)) AS original_lemma,
    NULLIF(btrim(translation), '') AS translation,
    NULLIF(btrim(definitions), '') AS definition_es,
    NULLIF(btrim(english_definition), '') AS definition_en,
    public.normalize_word_pos(pos) AS pos,
    NULLIF(btrim(sentence), '') AS example_sentence,
    NULLIF(btrim(english_sentence), '') AS example_sentence_en
  FROM public.words_import_raw
  WHERE rank IS NOT NULL
)
INSERT INTO public.words (
  rank,
  lemma,
  original_lemma,
  translation,
  definition_es,
  definition_en,
  pos,
  example_sentence,
  example_sentence_en
)
SELECT
  rank,
  lemma,
  original_lemma,
  translation,
  definition_es,
  definition_en,
  pos,
  example_sentence,
  example_sentence_en
FROM normalized
ON CONFLICT (rank) DO UPDATE
SET
  lemma = EXCLUDED.lemma,
  original_lemma = EXCLUDED.original_lemma,
  translation = EXCLUDED.translation,
  definition_es = EXCLUDED.definition_es,
  definition_en = EXCLUDED.definition_en,
  pos = EXCLUDED.pos,
  example_sentence = EXCLUDED.example_sentence,
  example_sentence_en = EXCLUDED.example_sentence_en;

DELETE FROM public.words w
WHERE NOT EXISTS (
  SELECT 1
  FROM public.words_import_raw raw
  WHERE raw.rank = w.rank
);

UPDATE public.word_forms
SET word_id = NULL
WHERE lang = 'es';

UPDATE public.word_forms wf
SET word_id = w.id
FROM public.words w
WHERE wf.lang = 'es'
  AND wf.word_id IS DISTINCT FROM w.id
  AND wf.lemma = w.lemma;

WITH fallback AS (
  SELECT
    wf.id AS word_form_id,
    (
      SELECT w.id
      FROM public.words w
      WHERE w.original_lemma = wf.lemma
      ORDER BY w.rank ASC
      LIMIT 1
    ) AS word_id
  FROM public.word_forms wf
  WHERE wf.lang = 'es'
    AND wf.word_id IS NULL
)
UPDATE public.word_forms wf
SET word_id = fallback.word_id
FROM fallback
WHERE wf.id = fallback.word_form_id
  AND fallback.word_id IS NOT NULL;

COMMIT;
"""
        )

    print(f"Wrote {output_sql}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
